add_subdirectory(asset)
add_subdirectory(audio)
add_subdirectory(core)
add_subdirectory(diagnostics)
add_subdirectory(graphics)
add_subdirectory(logger)
add_subdirectory(math)
add_subdirectory(physics)
add_subdirectory(reflection)
add_subdirectory(spdLog)
add_subdirectory(ui)
add_subdirectory(window)