name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-windows-vs2026:
    name: Windows (VS2026)
    # See https://github.com/actions/runner-images/tree/main#available-images
    runs-on: windows-2025-vs2026
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          vulkan_version: latest
          install_runtime: true
          cache: true

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 18 2026" -A x64

      - name: Build
        run: cmake --build build --config Debug

      - name: Run tests via CTest
        run: ctest --test-dir build --output-on-failure -C Debug
  
  build-ubuntu-gcc15:
    name: Ubuntu (gcc15)
    # See https://github.com/actions/runner-images/tree/main#available-images
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          vulkan_version: latest
          install_runtime: true
          cache: true

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure CMake
        run: cmake -S . -B build -G "Unix Makefiles" -A x64

      - name: Build
        run: cmake --build build --config Debug

      - name: Run tests via CTest
        run: ctest --test-dir build --output-on-failure -C Debug
