name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-windows-vs2026:
    name: Windows (VS2026)
    # See https://github.com/actions/runner-images/tree/main#available-images
    runs-on: windows-2025-vs2026
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          vulkan_version: latest
          install_runtime: true
          cache: true

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      # Setup vcpkg and enable native GitHub Actions Caching
      - name: Export GitHub Actions Cache URL for vcpkg
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 18 2026" -A x64
        env:
          # Tells vcpkg to read/write compiled binaries from GitHub Actions native cache
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"


      - name: Build
        run: cmake --build build --config Debug

      - name: Run tests via CTest
        run: ctest --test-dir build --output-on-failure -C Debug

  build-ubuntu-gcc15:
    name: Ubuntu (gcc15)
    # See https://github.com/actions/runner-images/tree/main#available-images
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libwayland-dev libwayland-bin wayland-protocols        \
                                  pkg-config libxkbcommon-dev libxkbcommon-x11-dev libx11-dev      \
                                  x11-xserver-utils libxrandr-dev libxinerama-dev libxcursor-dev   \
                                  libxi-dev libgl-dev

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          vulkan_version: latest
          install_runtime: true
          cache: true

      # Setup vcpkg and enable native GitHub Actions Caching
      - name: Export GitHub Actions Cache URL for vcpkg
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Configure CMake
        run: cmake -S . -B build
        env:
          # Tells vcpkg to read/write compiled binaries from GitHub Actions native cache
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

      - name: Build
        run: cmake --build build --config Debug

      - name: Run tests via CTest
        run: ctest --test-dir build --output-on-failure -C Debug
