on:
  push:
    branches:
      - main
      - add-doxygen-deploy

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Install dependencies
        run: uv sync --locked
      
      - name: Run tests
        working-directory: docs
        run: uv run sphinx-build -M html . _build
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_build/html' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
